package cluster

import (
	"archive/tar"
	"bytes"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/klauspost/compress/zstd"
	"github.com/philipparndt/go-logger"

	"k3c/config"
)

// Snapshot export/import: share a snapshot with another machine as a
// single file. Exports are always COLD — saved machine state is tied to
// the exact VM configuration (CPU count, memory, machine identifier) and
// never restores elsewhere. The host-side k3s-etc share is not exported
// either: it holds the sender's registry mirrors, CA bundle, and admin
// kubeconfig; the importer's own configuration applies instead.

const exportManifest = "export.yaml"

// exportable returns the snapshot files included in an export.
func exportable(dir string) []string {
	files := []string{"meta.yaml", serverRootfs}
	if _, err := os.Stat(filepath.Join(dir, registryRootfs)); err == nil {
		files = append(files, registryRootfs)
	}
	return files
}

// SnapshotExport writes a snapshot to a portable archive (tar+zstd).
func SnapshotExport(cfg *config.Config, name, out string) error {
	if err := validSnapshotName(name); err != nil {
		return err
	}
	dir := snapshotDir(cfg, name)
	if _, err := os.Stat(filepath.Join(dir, serverRootfs)); err != nil {
		return fmt.Errorf("snapshot '%s' not found for cluster '%s'", name, cfg.Cluster)
	}
	if out == "" {
		out = cfg.Cluster + "-" + name + ".k3csnap"
	}
	if snapshotIsWarm(dir) {
		logger.Info("machine state is machine-specific and not exported; the archive restores cold")
	}

	f, err := os.Create(out)
	if err != nil {
		return err
	}
	defer f.Close()
	zw, err := zstd.NewWriter(f)
	if err != nil {
		return err
	}
	tw := tar.NewWriter(zw)

	manifest := fmt.Sprintf("cluster: %s\nsnapshot: %s\nexported: %s\n",
		cfg.Cluster, name, time.Now().Format(time.RFC3339))
	if err := writeTarBytes(tw, exportManifest, []byte(manifest)); err != nil {
		return err
	}

	for _, fileName := range exportable(dir) {
		path := filepath.Join(dir, fileName)
		data := []byte(nil)
		if fileName == "meta.yaml" {
			// the export drops the machine state, so the archive is cold
			raw, err := os.ReadFile(path)
			if err != nil {
				return err
			}
			data = []byte(strings.ReplaceAll(string(raw), "mode: warm", "mode: cold"))
		}
		if data != nil {
			if err := writeTarBytes(tw, fileName, data); err != nil {
				return err
			}
			continue
		}
		if err := writeTarFile(tw, fileName, path); err != nil {
			return err
		}
	}

	if err := tw.Close(); err != nil {
		return err
	}
	if err := zw.Close(); err != nil {
		return err
	}
	if err := f.Close(); err != nil {
		return err
	}
	if info, err := os.Stat(out); err == nil {
		logger.Info(fmt.Sprintf("snapshot '%s' exported to %s (%.1f GB)", name, out, float64(info.Size())/1e9))
	}
	return nil
}

func snapshotIsWarm(dir string) bool {
	_, err := os.Stat(filepath.Join(dir, "server-"+vmstateFile))
	return err == nil
}

func writeTarBytes(tw *tar.Writer, name string, data []byte) error {
	if err := tw.WriteHeader(&tar.Header{Name: name, Mode: 0o644, Size: int64(len(data))}); err != nil {
		return err
	}
	_, err := tw.Write(data)
	return err
}

func writeTarFile(tw *tar.Writer, name, path string) error {
	f, err := os.Open(path)
	if err != nil {
		return err
	}
	defer f.Close()
	info, err := f.Stat()
	if err != nil {
		return err
	}
	logger.Info(fmt.Sprintf("packing %s (%.1f GB)", name, float64(info.Size())/1e9))
	if err := tw.WriteHeader(&tar.Header{Name: name, Mode: 0o644, Size: info.Size()}); err != nil {
		return err
	}
	_, err = io.Copy(tw, io.TeeReader(f, newProgress("packing "+name, info.Size())))
	return err
}

// progress logs a line every 10% of total bytes passing through.
type progress struct {
	label   string
	total   int64
	done    int64
	nextPct int64
}

func newProgress(label string, total int64) *progress {
	return &progress{label: label, total: total, nextPct: 10}
}

func (p *progress) Write(b []byte) (int, error) {
	p.add(int64(len(b)))
	return len(b), nil
}

func (p *progress) add(n int64) {
	p.done += n
	if p.total <= 0 {
		return
	}
	if pct := p.done * 100 / p.total; pct >= p.nextPct {
		logger.Info(fmt.Sprintf("%s: %d%%", p.label, pct))
		for p.nextPct <= pct {
			p.nextPct += 10
		}
	}
}

// SnapshotImport unpacks an exported snapshot archive for the cluster.
// The snapshot's host-side share content (registries, CA bundle) is taken
// from the importing cluster's configuration, not from the archive; the
// k3s admin kubeconfig is regenerated by k3s on the first boot.
func SnapshotImport(cfg *config.Config, file, name string) error {
	if _, err := os.Stat(cfg.K3sEtcDir()); err != nil {
		return fmt.Errorf("cluster '%s' has no node config yet; create the cluster first", cfg.Cluster)
	}

	f, err := os.Open(file)
	if err != nil {
		return err
	}
	defer f.Close()
	zr, err := zstd.NewReader(f)
	if err != nil {
		return fmt.Errorf("%s is not a k3c snapshot export: %w", file, err)
	}
	defer zr.Close()

	tmp, err := os.MkdirTemp(filepath.Join(cfg.BaseDir, "snapshots"), ".import-*")
	if err != nil {
		return err
	}
	defer os.RemoveAll(tmp)

	manifestName := ""
	tr := tar.NewReader(zr)
	for {
		hdr, err := tr.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			return err
		}
		switch hdr.Name {
		case exportManifest:
			data, err := io.ReadAll(io.LimitReader(tr, 1<<16))
			if err != nil {
				return err
			}
			for _, line := range strings.Split(string(data), "\n") {
				if v, ok := strings.CutPrefix(line, "snapshot: "); ok {
					manifestName = strings.TrimSpace(v)
				}
			}
		case "meta.yaml", serverRootfs, registryRootfs:
			logger.Info(fmt.Sprintf("unpacking %s (%.1f GB)", hdr.Name, float64(hdr.Size)/1e9))
			if err := writeSparseFile(filepath.Join(tmp, hdr.Name), tr, hdr.Size); err != nil {
				return err
			}
		default:
			return fmt.Errorf("unexpected entry in archive: %s", hdr.Name)
		}
	}
	if _, err := os.Stat(filepath.Join(tmp, serverRootfs)); err != nil {
		return fmt.Errorf("%s contains no server root filesystem", file)
	}

	if name == "" {
		name = manifestName
	}
	if name == "" {
		name = strings.TrimSuffix(filepath.Base(file), filepath.Ext(file))
	}
	if err := validSnapshotName(name); err != nil {
		return err
	}
	dir := snapshotDir(cfg, name)
	if _, err := os.Stat(dir); err == nil {
		return fmt.Errorf("snapshot '%s' already exists for cluster '%s'", name, cfg.Cluster)
	}

	// the restore copies k3s-etc onto the share: use this cluster's own
	// node config; k3s.yaml is omitted so k3s writes a fresh kubeconfig
	// matching the restored cluster's CA on the first boot
	if err := copyDir(cfg.K3sEtcDir(), filepath.Join(tmp, "k3s-etc")); err != nil {
		return err
	}
	_ = os.Remove(filepath.Join(tmp, "k3s-etc", "k3s.yaml"))

	if err := os.MkdirAll(filepath.Dir(dir), 0o755); err != nil {
		return err
	}
	if err := os.Rename(tmp, dir); err != nil {
		return err
	}
	logger.Info("snapshot '" + name + "' imported for cluster '" + cfg.Cluster + "' (restore with: k3c snapshot restore " + name + ")")
	return nil
}

// writeSparseFile writes r to path, seeking over zero blocks so large
// mostly-empty disk images do not materialize on disk.
func writeSparseFile(path string, r io.Reader, size int64) error {
	f, err := os.OpenFile(path, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 0o644)
	if err != nil {
		return err
	}
	defer f.Close()
	buf := make([]byte, 1<<20)
	zero := make([]byte, 1<<20)
	prog := newProgress("unpacking "+filepath.Base(path), size)
	var offset int64
	for offset < size {
		n, err := io.ReadFull(r, buf)
		if err == io.ErrUnexpectedEOF || err == io.EOF {
			if n == 0 {
				break
			}
		} else if err != nil {
			return err
		}
		chunk := buf[:n]
		if bytes.Equal(chunk, zero[:n]) {
			if _, err := f.Seek(int64(n), io.SeekCurrent); err != nil {
				return err
			}
		} else {
			if _, err := f.Write(chunk); err != nil {
				return err
			}
		}
		offset += int64(n)
		prog.add(int64(n))
	}
	if err := f.Truncate(size); err != nil {
		return err
	}
	return f.Close()
}
