name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Build
        run: go build -v -ldflags "-s -w -X k3c/version.Version=$GITHUB_REF -X k3c/version.GitCommit=${GITHUB_SHA::8}" .

      - name: Test
        run: go test ./...